parameters:
  # display composant feature for LMS Activities's bf_contenu
  actionbuilder_textarea_name: 'bf_contenu'
  lms_config:
    # if true, tabs can be used in LMS activities (MyActivity2, MyActivity3... refer to the parent activity MyActivity)
    tabs_enabled: true
    # if true, the activity title is automatically added at the begin of the entry page
    display_activity_title: true
    # if you change activitie_form_id, module_form_id or course_form_id, you have also to rename the corresponding
    # bazar template : tools/lms/templates/bazar/fiche-XXXX.tpl.html
    activity_form_id: 1201
    module_form_id: 1202
    course_form_id: 1203
    use_yeswiki_comments: false
    # maximum size for both width and height to render the module images in the course entry
    module_image_size_in_course: 400
    # only for developers : displays the lms pages as a user sees them
    save_progress_for_admins: false
    # for learner dashboard
    use_only_custom_elapsed_time: true
    display_activity_elapsed_time: false
    # if true, the extra activities can be added to the courses
    extra_activity_enabled: false
    # show activities without context when one course is scripted (false = to be sure no activity is readable)
    show_activities_without_context_or_learner: true
    # activate navigation conditions to check if user is allowed to view next activity
    activity_navigation_conditions_enabled: false

services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Lms\Service\:
    resource: 'services/*'

  YesWiki\Lms\Controller\:
    resource: 'controllers/*'
